export const NODE_DIMENSIONS = {
  VPC: {
    DEFAULT_WIDTH: 1200,
    DEFAULT_HEIGHT: 1000,
    INFO_CARD_HEIGHT: 200,
    PADDING: 40
  },
  SUBNET: {
    DEFAULT_WIDTH: 800,
    DEFAULT_HEIGHT: 500,
    INFO_CARD_HEIGHT: 150,
    PADDING: 30
  },
  RESOURCE: {
    DEFAULT_WIDTH: 400,
    DEFAULT_HEIGHT: 200,
    MARGIN: 40,
    PADDING: 20
  },
  HEADER: {
    DEFAULT_WIDTH: 400,
    DEFAULT_HEIGHT: 200,
    PADDING: 20
  }
}; 