version: '3'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/your_password
    ports:
      - "7687:7687"  # Bolt protocol
      - "7474:7474"  # HTTP
    volumes:
      - neo4j_data:/data
    networks:
      - neo4j_network

volumes:
  neo4j_data:

networks:
  neo4j_network:
    driver: bridge
